// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/account/signup": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/how-it-works": {
    params: {};
  };
  "/shop": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/account/logout" | "/account/signin" | "/account/signup" | "/contact" | "/dashboard" | "/how-it-works" | "/shop" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./about/page.jsx": {
    id: "about/page";
    page: "/about";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./account/signup/page.jsx": {
    id: "account/signup/page";
    page: "/account/signup";
  };
  "./contact/page.jsx": {
    id: "contact/page";
    page: "/contact";
  };
  "./dashboard/page.jsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./how-it-works/page.jsx": {
    id: "how-it-works/page";
    page: "/how-it-works";
  };
  "./shop/page.jsx": {
    id: "shop/page";
    page: "/shop";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "about/page": typeof import("./src/app/./about/page.jsx");
  "account/logout/page": typeof import("./src/app/./account/logout/page.jsx");
  "account/signin/page": typeof import("./src/app/./account/signin/page.jsx");
  "account/signup/page": typeof import("./src/app/./account/signup/page.jsx");
  "contact/page": typeof import("./src/app/./contact/page.jsx");
  "dashboard/page": typeof import("./src/app/./dashboard/page.jsx");
  "how-it-works/page": typeof import("./src/app/./how-it-works/page.jsx");
  "shop/page": typeof import("./src/app/./shop/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};